### PR TITLE
Ginkgo Ecommerce branch with basket metadata fix 

### PR DESCRIPTION
**Pull request by amirtds**

### CODE REVIEW

**Comment by amirtds** [comment]
[(2) UW: push ecommerce Sentry integration](https://trello.com/c/8akiFRJO/2731-2-uw-push-ecommerce-sentry-integration)

**Comment by OmarIthawi** [comment]
@amirtds care to explain a bit more? I understand the goal, but the implementation is a bit complication.

**Comment by tkeemon** [comment]
@amirtds it looks like you've got two fixes in place here: 

1. Add Sentry integration to Ecommerce
2. Pull course metadata from the LMS instead of [course-discovery](https://github.com/edx/course-discovery)

Do you still need to account for `#2` if this is a Ginkgo deployment?

**Comment by amirtds** [comment]
@tkeemon `#1` is still needed but we can discard `#2` for now and i can start test ecommerce on Ginkgo to make sure if discovery runs if yes there is no need to have `#2`

**Comment by bryanlandia** [comment]
@amirtds - checking in on this PR.  Did you have a chance to look into removing '#2' changes?

**Comment by bryanlandia** [comment]
@amirtds OK, from your [Trello comment](https://trello.com/c/8akiFRJO/2731-2-uw-push-ecommerce-sentry-integration#comment-5b57e42d9818a53d235de54e) sounds like you checked and `#2` is still needed and you have  tested in a Ginkgo instance.  

I see generally the switch fetching from LMS instead of course_discovery but there's a lot of changes here that I don't really understand.  

Could you either add some of your own inline GitHub comments in the code, or add a more detailed description so we can understand better?

**Pull request closed without merging**
